/**
 * The Korean voices of the Gemini TTS Extended Voice Library, as `GET https://generativelanguage.googleapis.com/v1beta/voices?language_code=ko-KR`
 * listed them on 2026-10-07 (117 voices, all Seoul Korean, usable by gemini-3.8-flash-tts on the Gemini API and on Vertex AI).
 */
export type VoiceGender = "male" | "female" | "neutral";
export interface Voice { readonly id: string; readonly name: string; readonly gender: VoiceGender; readonly pitch: "low" | "medium" | "high" }
export const KOREAN_VOICES: readonly Voice[] = [
  { id: "ko-kr-advisor-1", name: "Authoritative Advisor 1", gender: "male", pitch: "low" },
  { id: "ko-kr-advisor-2", name: "Authoritative Advisor 2", gender: "female", pitch: "medium" },
  { id: "ko-kr-advisor-3", name: "Authoritative Advisor 3", gender: "male", pitch: "low" },
  { id: "ko-kr-advisor-4", name: "Authoritative Advisor 4", gender: "female", pitch: "high" },
  { id: "ko-kr-advisor-5", name: "Authoritative Advisor 5", gender: "male", pitch: "low" },
  { id: "ko-kr-advisor-6", name: "Authoritative Advisor 6", gender: "female", pitch: "medium" },
  { id: "ko-kr-advisor-7", name: "Authoritative Advisor 7", gender: "female", pitch: "medium" },
  { id: "ko-kr-advisor-8", name: "Authoritative Advisor 8", gender: "male", pitch: "low" },
  { id: "ko-kr-advisor-9", name: "Authoritative Advisor 9", gender: "female", pitch: "medium" },
  { id: "ko-kr-assistant-1", name: "Digital Assistant 1", gender: "male", pitch: "low" },
  { id: "ko-kr-assistant-2", name: "Digital Assistant 2", gender: "female", pitch: "high" },
  { id: "ko-kr-assistant-3", name: "Digital Assistant 3", gender: "female", pitch: "low" },
  { id: "ko-kr-assistant-4", name: "Digital Assistant 4", gender: "male", pitch: "low" },
  { id: "ko-kr-assistant-5", name: "Digital Assistant 5", gender: "male", pitch: "low" },
  { id: "ko-kr-assistant-6", name: "Digital Assistant 6", gender: "female", pitch: "medium" },
  { id: "ko-kr-assistant-7", name: "Digital Assistant 7", gender: "female", pitch: "medium" },
  { id: "ko-kr-assistant-8", name: "Digital Assistant 8", gender: "male", pitch: "low" },
  { id: "ko-kr-assistant-9", name: "Digital Assistant 9", gender: "female", pitch: "medium" },
  { id: "ko-kr-assistant-10", name: "Digital Assistant 10", gender: "male", pitch: "low" },
  { id: "ko-kr-assistant-11", name: "Digital Assistant 11", gender: "female", pitch: "high" },
  { id: "ko-kr-assistant-12", name: "Digital Assistant 12", gender: "male", pitch: "low" },
  { id: "ko-kr-commercial-1", name: "Commercial Voiceover 1", gender: "female", pitch: "high" },
  { id: "ko-kr-commercial-2", name: "Commercial Voiceover 2", gender: "male", pitch: "low" },
  { id: "ko-kr-commercial-3", name: "Commercial Voiceover 3", gender: "female", pitch: "low" },
  { id: "ko-kr-commercial-4", name: "Commercial Voiceover 4", gender: "male", pitch: "medium" },
  { id: "ko-kr-commercial-5", name: "Commercial Voiceover 5", gender: "male", pitch: "low" },
  { id: "ko-kr-commercial-6", name: "Commercial Voiceover 6", gender: "female", pitch: "medium" },
  { id: "ko-kr-commercial-7", name: "Commercial Voiceover 7", gender: "male", pitch: "low" },
  { id: "ko-kr-commercial-8", name: "Commercial Voiceover 8", gender: "male", pitch: "low" },
  { id: "ko-kr-commercial-9", name: "Commercial Voiceover 9", gender: "female", pitch: "high" },
  { id: "ko-kr-commercial-10", name: "Commercial Voiceover 10", gender: "male", pitch: "low" },
  { id: "ko-kr-commercial-11", name: "Commercial Voiceover 11", gender: "female", pitch: "medium" },
  { id: "ko-kr-commercial-12", name: "Commercial Voiceover 12", gender: "female", pitch: "high" },
  { id: "ko-kr-concierge-1", name: "Concierge 1", gender: "female", pitch: "medium" },
  { id: "ko-kr-concierge-2", name: "Concierge 2", gender: "male", pitch: "low" },
  { id: "ko-kr-concierge-3", name: "Concierge 3", gender: "male", pitch: "low" },
  { id: "ko-kr-concierge-4", name: "Concierge 4", gender: "female", pitch: "high" },
  { id: "ko-kr-concierge-5", name: "Concierge 5", gender: "female", pitch: "medium" },
  { id: "ko-kr-concierge-6", name: "Concierge 6", gender: "male", pitch: "low" },
  { id: "ko-kr-concierge-7", name: "Concierge 7", gender: "male", pitch: "low" },
  { id: "ko-kr-concierge-8", name: "Concierge 8", gender: "female", pitch: "high" },
  { id: "ko-kr-concierge-9", name: "Concierge 9", gender: "male", pitch: "low" },
  { id: "ko-kr-concierge-10", name: "Concierge 10", gender: "male", pitch: "low" },
  { id: "ko-kr-concierge-11", name: "Concierge 11", gender: "female", pitch: "medium" },
  { id: "ko-kr-concierge-12", name: "Concierge 12", gender: "female", pitch: "high" },
  { id: "ko-kr-csagent-1", name: "Call Center Agent 1", gender: "female", pitch: "high" },
  { id: "ko-kr-csagent-2", name: "Call Center Agent 2", gender: "male", pitch: "low" },
  { id: "ko-kr-csagent-3", name: "Call Center Agent 3", gender: "female", pitch: "low" },
  { id: "ko-kr-csagent-4", name: "Call Center Agent 4", gender: "male", pitch: "low" },
  { id: "ko-kr-csagent-5", name: "Call Center Agent 5", gender: "female", pitch: "medium" },
  { id: "ko-kr-csagent-6", name: "Call Center Agent 6", gender: "male", pitch: "low" },
  { id: "ko-kr-csagent-7", name: "Call Center Agent 7", gender: "female", pitch: "high" },
  { id: "ko-kr-csagent-8", name: "Call Center Agent 8", gender: "male", pitch: "low" },
  { id: "ko-kr-csagent-9", name: "Call Center Agent 9", gender: "female", pitch: "high" },
  { id: "ko-kr-csagent-10", name: "Call Center Agent 10", gender: "female", pitch: "medium" },
  { id: "ko-kr-csagent-11", name: "Call Center Agent 11", gender: "male", pitch: "low" },
  { id: "ko-kr-csagent-12", name: "Call Center Agent 12", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-1", name: "Podcaster 1", gender: "female", pitch: "high" },
  { id: "ko-kr-podcaster-2", name: "Podcaster 2", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-3", name: "Podcaster 3", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-4", name: "Podcaster 4", gender: "female", pitch: "high" },
  { id: "ko-kr-podcaster-5", name: "Podcaster 5", gender: "female", pitch: "medium" },
  { id: "ko-kr-podcaster-6", name: "Podcaster 6", gender: "female", pitch: "high" },
  { id: "ko-kr-podcaster-7", name: "Podcaster 7", gender: "female", pitch: "high" },
  { id: "ko-kr-podcaster-8", name: "Podcaster 8", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-9", name: "Podcaster 9", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-10", name: "Podcaster 10", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-11", name: "Podcaster 11", gender: "male", pitch: "low" },
  { id: "ko-kr-podcaster-12", name: "Podcaster 12", gender: "female", pitch: "high" },
  { id: "ko-kr-storyteller-1", name: "Storyteller 1", gender: "male", pitch: "low" },
  { id: "ko-kr-storyteller-2", name: "Storyteller 2", gender: "female", pitch: "high" },
  { id: "ko-kr-storyteller-3", name: "Storyteller 3", gender: "male", pitch: "low" },
  { id: "ko-kr-storyteller-4", name: "Storyteller 4", gender: "female", pitch: "medium" },
  { id: "ko-kr-storyteller-5", name: "Storyteller 5", gender: "male", pitch: "medium" },
  { id: "ko-kr-storyteller-6", name: "Storyteller 6", gender: "female", pitch: "high" },
  { id: "ko-kr-storyteller-7", name: "Storyteller 7", gender: "female", pitch: "medium" },
  { id: "ko-kr-storyteller-8", name: "Storyteller 8", gender: "male", pitch: "low" },
  { id: "ko-kr-storyteller-9", name: "Storyteller 9", gender: "female", pitch: "high" },
  { id: "ko-kr-storyteller-10", name: "Storyteller 10", gender: "male", pitch: "low" },
  { id: "ko-kr-storyteller-11", name: "Storyteller 11", gender: "female", pitch: "medium" },
  { id: "ko-kr-storyteller-12", name: "Storyteller 12", gender: "male", pitch: "low" },
  { id: "ko-kr-techagent-1", name: "Tech Advisor 1", gender: "female", pitch: "medium" },
  { id: "ko-kr-techagent-2", name: "Tech Advisor 2", gender: "male", pitch: "low" },
  { id: "ko-kr-techagent-3", name: "Tech Advisor 3", gender: "male", pitch: "low" },
  { id: "ko-kr-techagent-4", name: "Tech Advisor 4", gender: "female", pitch: "high" },
  { id: "ko-kr-techagent-5", name: "Tech Advisor 5", gender: "male", pitch: "low" },
  { id: "ko-kr-techagent-6", name: "Tech Advisor 6", gender: "male", pitch: "medium" },
  { id: "ko-kr-techagent-7", name: "Tech Advisor 7", gender: "female", pitch: "high" },
  { id: "ko-kr-techagent-8", name: "Tech Advisor 8", gender: "female", pitch: "medium" },
  { id: "ko-kr-techagent-9", name: "Tech Advisor 9", gender: "male", pitch: "low" },
  { id: "ko-kr-techagent-10", name: "Tech Advisor 10", gender: "female", pitch: "low" },
  { id: "ko-kr-techagent-11", name: "Tech Advisor 11", gender: "male", pitch: "low" },
  { id: "ko-kr-techagent-12", name: "Tech Advisor 12", gender: "female", pitch: "high" },
  { id: "ko-kr-training-1", name: "Training Voiceover 1", gender: "female", pitch: "medium" },
  { id: "ko-kr-training-2", name: "Training Voiceover 2", gender: "male", pitch: "low" },
  { id: "ko-kr-training-3", name: "Training Voiceover 3", gender: "female", pitch: "low" },
  { id: "ko-kr-training-4", name: "Training Voiceover 4", gender: "male", pitch: "medium" },
  { id: "ko-kr-training-5", name: "Training Voiceover 5", gender: "male", pitch: "low" },
  { id: "ko-kr-training-6", name: "Training Voiceover 6", gender: "female", pitch: "low" },
  { id: "ko-kr-training-7", name: "Training Voiceover 7", gender: "female", pitch: "high" },
  { id: "ko-kr-training-8", name: "Training Voiceover 8", gender: "female", pitch: "high" },
  { id: "ko-kr-training-9", name: "Training Voiceover 9", gender: "female", pitch: "high" },
  { id: "ko-kr-training-10", name: "Training Voiceover 10", gender: "neutral", pitch: "high" },
  { id: "ko-kr-training-11", name: "Training Voiceover 11", gender: "male", pitch: "low" },
  { id: "ko-kr-training-12", name: "Training Voiceover 12", gender: "male", pitch: "low" },
  { id: "ko-kr-tutor-1", name: "Tutor 1", gender: "male", pitch: "low" },
  { id: "ko-kr-tutor-2", name: "Tutor 2", gender: "female", pitch: "high" },
  { id: "ko-kr-tutor-3", name: "Tutor 3", gender: "female", pitch: "medium" },
  { id: "ko-kr-tutor-4", name: "Tutor 4", gender: "male", pitch: "low" },
  { id: "ko-kr-tutor-5", name: "Tutor 5", gender: "female", pitch: "high" },
  { id: "ko-kr-tutor-6", name: "Tutor 6", gender: "male", pitch: "medium" },
  { id: "ko-kr-tutor-7", name: "Tutor 7", gender: "female", pitch: "medium" },
  { id: "ko-kr-tutor-8", name: "Tutor 8", gender: "female", pitch: "high" },
  { id: "ko-kr-tutor-9", name: "Tutor 9", gender: "male", pitch: "low" },
  { id: "ko-kr-tutor-10", name: "Tutor 10", gender: "female", pitch: "high" },
  { id: "ko-kr-tutor-11", name: "Tutor 11", gender: "male", pitch: "low" },
  { id: "ko-kr-tutor-12", name: "Tutor 12", gender: "male", pitch: "low" },
];
